/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#2a3439",
        "surface-tint": "#0061a4",
        "secondary-fixed": "#e0e3e6",
        "error-dim": "#4e0309",
        "on-primary-fixed": "#004171",
        "tertiary": "#53616a",
        "tertiary-fixed": "#e1f0fb",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e0e3e6",
        "surface-container-highest": "#d9e4ea",
        "on-secondary": "#f7f9fc",
        "on-error-container": "#752121",
        "on-secondary-container": "#4f5255",
        "on-background": "#2a3439",
        "primary-dim": "#005590",
        "on-tertiary": "#f4faff",
        "error-container": "#fe8983",
        "primary-fixed-dim": "#b8d7ff",
        "tertiary-fixed-dim": "#d3e2ed",
        "secondary": "#5c5f62",
        "surface-container-low": "#f0f4f7",
        "on-tertiary-fixed": "#3a4851",
        "secondary-fixed-dim": "#d2d5d7",
        "surface": "#f7f9fb",
        "outline": "#717c82",
        "on-tertiary-container": "#4c5a63",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "surface-container": "#e8eff3",
        "primary-fixed": "#d1e4ff",
        "on-primary-fixed-variant": "#005e9f",
        "inverse-surface": "#0b0f10",
        "secondary-dim": "#505356",
        "on-primary-container": "#00548f",
        "on-error": "#fff7f6",
        "tertiary-container": "#e1f0fb",
        "surface-container-high": "#e1e9ee",
        "tertiary-dim": "#47555e",
        "primary": "#0061a4",
        "surface-variant": "#d9e4ea",
        "on-surface-variant": "#566166",
        "on-primary": "#f5f8ff",
        "inverse-on-surface": "#9a9d9f",
        "on-secondary-fixed": "#3c4042",
        "outline-variant": "#a9b4b9",
        "error": "#9f403d",
        "primary-container": "#d1e4ff",
        "on-secondary-fixed-variant": "#595c5e",
        "surface-dim": "#cfdce3",
        "on-tertiary-fixed-variant": "#56656e",
        "inverse-primary": "#2498f5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      keyframes: {
        fadeSlideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-slide-up": "fadeSlideUp 0.3s ease",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
}
